### ISSUE TITLE
Eukaryotes ?

### ISSUE THREAD

**Issue by colindaven** [Sheikhizadeh/pantools#1]
Interesting work. Has this been tested on eukaryotes or is it more aimed towards bacteria ?

Thanks,
Colin

**Comment by Sheikhizadeh** [comment]
Dear Colin,

Thank you for your interest. We tested it on large datasets like 93 yeasts, 18 Arabidopsis Thalianas and even 7 humans. Our goal is to build large plant pan-genomes, annotate and do comparative genomics with them. You can find more about it here:

http://bioinformatics.oxfordjournals.org/content/32/17/i487.full

Regards,

Siavash

## 

Siavash Sheikhizadeh Anari
Bioinformatics Group
Wageningen University
Droevendaalsesteeg 1, 6708PB
Building/Room: 107/W1.Ad.054

**Comment by colindaven** [comment]
Thanks, thats helpful
