### ISSUE TITLE
kmer 257 not possible, 256 is max

### ISSUE THREAD

**Issue by colindaven** [Sheikhizadeh/pantools#2]
This command throws the following error. K=256 works.

java -Xmx450g -jar /home/bioinformatics/NAS01/programs/pantools/pantools/dist/pantools.jar build 257 ./db  input_fasta.fofn

------------------------------- PanTools -------------------------------
K should be between 0 and 257 !

**Comment by Sheikhizadeh** [comment]
Dear Colin,

That's true, the maximum value for K is 256, This limitation is posed by KMC2, the kmer counting tool we use for building the kmer index. Actually, it is much larger than what we need for building a pangenome. Choosing larger valued for K decrease the connectivity of the pangenome and you would not detect the shared sequences smaller than K. In the paper you can see that even for 1000 human genomes K=48 suffices.

Cheers,

Siavash

## 

Siavash Sheikhizadeh Anari
Bioinformatics Group
Wageningen University
Droevendaalsesteeg 1, 6708PB
Building/Room: 107/W1.Ad.054
